version: '3'

services:
  sxsvs:
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      SDATABASE_URL: postgresql://postgres:qwe123@db/postgres
      PYTHONUNBUFFERED: 1
  db:
    image: postgres:${PG_VERSION:-11-beta4-alpine}
    environment:
      POSTGRES_PASSWORD: qwe123
