"""empty message

Revision ID: 79ed16a74f3b
Revises: 3eaf629ba390
Create Date: 2019-03-25 10:20:28.135034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ed16a74f3b'
down_revision = '3eaf629ba390'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gas_stations', sa.Column('is_open', sa.Boolean(), nullable=True))
    op.add_column('car_type', sa.Column('fuel_type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'car_type', 'fuel_types', ['fuel_type'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
    connection = op.get_bind()
    ADD_FUEL_TYPES = ["A92", "A95", "A98", "DIESEL"]
    cnt = 1
    for i in ADD_FUEL_TYPES:
        connection.execute(f"INSERT INTO fuel_types (id, name) values ({cnt},'{i}');")
        cnt = cnt +1

    CAR_TYPES = [
        {"name":"FORD", "fuel":4,"fuel100":15},
        {"name":"KIA", "fuel":2,"fuel100":10},
        {"name":"LADA", "fuel":2,"fuel100":9},
        {"name":"Jeep", "fuel":3,"fuel100":17},
    ]
    cnt = 1
    for i in CAR_TYPES:
        connection.execute(f"INSERT INTO car_type (id, name, fuel_type, liter_per_km) values ({cnt},'{i['name']}',{i['fuel']},{i['fuel100']});")
        cnt = cnt +1

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gas_stations', 'is_open')
    op.drop_constraint(None, 'car_type', type_='foreignkey')
    op.drop_column('car_type', 'fuel_type')
    # ### end Alembic commands ###
